### ISSUE TITLE
Deployment is failing with Template format error with sceptre 2.7.1 version

### ISSUE THREAD

**Issue by nilbante** [Sceptre/sceptre#1186]
We are using sceptre to deploy AWS stack through cloud formation templates. It was working till we were using 2.6.3 but when we upgraded to 2.7.1, deployment is failing with the below error. Is there anything changed that is causing this. 
 When we downgraded to 2.6.3, its worked as expected.

[2021-12-13 05:21:33] - test/nw-saz - Creating Stack
"An error occurred (ValidationError) when calling the CreateStack operation: Template format error: YAML not well-formed. (line 12, column 1)"

[root@ScaleCon35 sceptre]# python3 --version
Python 3.6.8

[root@ScaleCon35 sceptre]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)

**Comment by jfalkenstein** [comment]
Hi @nilbante, are you able to post the whole template here? If not, what about lines 8 - 16?

Also, I'm assuming you're using `sceptre launch` to deploy, right?

**Comment by nilbante** [comment]
```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a Single-AZ, Single-subnet VPC infrastructure with
  managed NAT gateway and carries out IBM Spectrum Scale cloud deployment
  via EC2 Controller Node.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
   ```
We are using sceptre to launch deploy.

**Comment by jfalkenstein** [comment]
Hmmm... nothing looks off about that to me (assuming `Label:` has a value below it). I've found that quoting the "AWSTemplateFormatVersion" can help. I've encountered some weird issues where `2010-09-09` is actually interpreted by pyyaml as a date, which can blow up things expecting them to be strings. But honestly, none of that seems practical. I'm not sure at this point what is causing your issue. What happens if you write a quick script that reads in the template file and runs `yaml.load()` on it? Do you get a validation error then?

**Comment by zaro0508** [comment]
Sceptre no longer support python 2.7
