### ISSUE TITLE
_update _create hooks acting like _launch

### ISSUE THREAD

**Issue by avatarworf** [Sceptre/sceptre#1215]
During the migration from sceptre v1 to v3, the actions of hooks looks too have changed. 
 any `after_update` or `after_create` hook actions execute without regards to the state change of the sceptre launch results.  In effect the logic works like like the hook was attached to an `after_launch` action.

### Environment
* version of sceptre (v3.0.0)
* version of python (v3.7.10)
* Amazon Linux 2

### Steps to reproduce
With a Stack Configuration file resembling the following `governance/global/stack.yaml`: 

```yaml
---
template_path: governance/cloudformation.yaml
hooks:
  after_create:
    - !cmd "echo after_create"
  after_update:
    - !cmd "echo after_update"
stack_tags:
  costTag: money-pot-1
```

### Expected behaviour

Since no changes exist in the Cloudformation nor changes within the sceptre stack config file, the expected behaviour as previous seen in v1

```
[2022-04-12 16:15:22] - sceptre.stack - governance/global/stack - Launching stack
[2022-04-12 16:15:23] - sceptre.stack - governance/global/stack - Stack is in the UPDATE_COMPLETE state
[2022-04-12 16:15:23] - sceptre.stack - governance/global/stack - Updating stack
[2022-04-12 16:15:23] - sceptre.stack - governance/global/stack - No updates to perform.
```
and zero indication of an hook being triggered.

### Actual behaviour

```
[2022-04-12 12:12:16] - Reading in 'governance/global/stack.yaml' files...
[2022-04-12 12:12:16] - Config: {'project_path': '/var/lib/........t'}}
[2022-04-12 12:12:16] - governance/global/stack - Launching Stack
[2022-04-12 12:12:16] - governance/global/stack - Stack is in the UPDATE_COMPLETE state
[2022-04-12 12:12:16] - governance/global/stack - Updating Stack
[2022-04-12 12:12:17] - governance/global/stack - No updates to perform.
after_create
after_update
```

### Previous related tickets

#219 - Originally raised by my manager, this issue lead to the `after_launch` hook, which is a wonderful thing, which we will probably implement.

#712 - was raised with the same issue, but was cut short by @ngfgrant with the point that the hook needs to simply have additional logic to handle the case of always being executed.  This seems incorrect by my view as the purpose of the `after_create` and `after_update` per the [docs](https://docs.sceptre-project.org/3.0.0/docs/hooks.html#hook-points), is to only trigger when the initial creation of the stack is made or a change is performed and the stack updated.

#358 - indicated a similar always running hook.  If we truely need to change the code of the Hook to anticipate the state change. How would this be noticed.

Previous we had duplicate hooks triggered against the same code cause the `after_create` and `after_update` where never executed for the same initial or update stack events.

Therefore it seems like regardless of which hook point style is used it is always executed. The Cloudformation Event stack output itself shows no new events.

**Comment by jfalkenstein** [comment]
Hi @avatarworf, so if you look at the [code for the `launch` action](https://github.com/Sceptre/sceptre/blob/master/sceptre/plan/actions.py#L178~L225), "launch" is a bit of a composite command. Depending on the specific state of the stack being launched, it could involve one of the following:
* Create (if existing stack doesn't exist)
* Delete then Create (if the stack exists but is in rollback complete state)
* An update (if the stack already exists)

before_launch and after_launch apply to the whole unit of work, regardless of what that entailed. However, the launch command will indeed also fire before/after_create (when creation is occurring), before/after_update (when updation is occurring), before/after_delete (when deletion is occurring). So if you want to target hooks specifically to one of _those_ actions, you can do that and ignore before/after_launch. 

Furthermore, there's indeed no logic about whether or not the action actually _did_ anything; Even if there were no changes, the hook will still fire. This is because the hook code is pretty simply a set of bookends around decorated functions: https://github.com/Sceptre/sceptre/blob/master/sceptre/hooks/__init__.py#L94~L109


Anyway, with all that said, I'm just describing what currently _is_ Sceptre's behavior. However, I'm not exactly sure what the behavior you are requesting or believe _should_ be present. If I haven't addressed your concerns, could you describe in more detail?

**Comment by avatarworf** [comment]
Hi @jfalkenstein, thanks for your in-depth reply 

As in my example sceptre stack config, if I have both an `after_create` and an `after_update`. Since these are bookending the `sceptre launch` cli command, and given that the stack already exists.  Both of these hooks fire, even tho the stack is not being created.

Now that you shared this [code ref](https://github.com/Sceptre/sceptre/blob/master/sceptre/hooks/__init__.py#L94~L109) is it true, then that the hooks specifically relate to the CLI command?  
If I ran `sceptre delete`
* I gather only after/before_delete
If I ran `sceptre create`
* I gather only after/before_create
If I ran `sceptre update`
* I gather only after/before_update
So `sceptre launch`:
* why would this execute all hooks, but my experiment after/before_launch, after/before_create, after/before_update

Given all that, I see the logical simplification performed when `sceptre launch-env` was dropped in the migration from v1 to v3.  Which would have noticed that a new stack was simply updated and only trigger the `after_update` hook (as an example)

Are there any techniques possible from within the Hook, using the `self.stack.X`. Or will i need to recode the hooks to do some advanced checking.  As an example, I have a hook which imports an ACM certificate, cause cloudformation doesn't support the import.  This process currently re-imports each time the stack is launched - updating the configuration within the ACM. [ not detrimental , but not ideal ]

Perhaps what I'm after is a hook like `after_change`, which triggers when a stack is created or updated, regardless of sceptre CLI command which triggered it

**Comment by avatarworf** [comment]
After reverifying my launch conditions, I noticed more stacks being launched when targeting a specific 'environment'.  Therefore I was seeing output from two executions of the hook due to two different 'environment' launches.

Still be interested in knowing if there is anything in `self.stack.X` to determine that no changes where performed

**Comment by jfalkenstein** [comment]
No, hooks do not have any logic to determine if changes were actually made or not; before_update and after_update will ALWAYS fire before an update, regardless of whether anything is _actually_ updated. Implementing that logic would be particularly tricky, I think, based upon how the code is currently written. My recommendation would be to pursue one of the following approaches in this situation:
1. Make your hook able to fire every single time, whether changes are made or not, without raising errors. Most of the time, this works just fine for my hooks.
2. Custom hooks have access to the stack and the stack's ConnectionManager. You could make custom hooks that are capable of querying AWS for the current state of stack resources to make determinations as to whether or not they should do anything further. On occasion, I use this approach, where it matters. 
3. Put your hook behind a --var flag or an environment variable so that it only fires when explicitly indicated as such. For example:

```yaml

hooks:
    after_update:
        {% if var.run_my_special_hook|default(False) %}
        - !my_special_hook
        {% endif %}
```

Doing something like this gives you more explicit control over whether the hook will fire or not.

**Comment by avatarworf** [comment]
@jfalkenstein thanks for the explanation. I'll approach using suggestion 2, where needed
