### ISSUE TITLE
Sceptre launch exit code 1

### ISSUE THREAD

**Issue by driverpt** [Sceptre/sceptre#1339]
### Subject of the issue
Sceptre is returning Exit Code 1. Causing our CI Jobs to fail

### Your environment
* version of sceptre 4.1.0
* version of python 3.10
* which OS/distro Amazon Linux 2

### Steps to reproduce
Call `sceptre launch`

### Expected behaviour
Exit code 0 if everything went well

### Actual behaviour
Exit code 1 after successful deployment

### Notes
Might be relared to #688

**Comment by jfalkenstein** [comment]
Hi @driverpt, could you run your `launch` command with the `--debug` flag and post the full output to this issue? Of course, if there are any credentials/sensitive bits you should redact those. But to my knowledge, there isn't an issue where a successful launch returns a 1 code (otherwise a lot of my own company's pipelines would be failing). I suspect there's something going on that is causing a failure.

Just because a single stack fails to deploy doesn't Mean Sceptre stops deploying the remaining stacks. The result can be that it LOOKS like a success unless you carefully read the logs. But if a single deployment fails, it WILL return a 1. I suspect this is what's happening. Looking at the full debug launch logs will help indicate the problem, though.

**Comment by driverpt** [comment]
It's fixed (PEBCAK). My bad. There as a failing `Fn::Transform` :(
