### ISSUE TITLE
python < 3.12 causes issues with other poetry projects, can you use < 4.0

### ISSUE THREAD

**Issue by pc-fmarin** [Sceptre/sceptre#1353]
### Python <3.12 causes dependency issues
We have a poetry app w/ sceptre dependencies with python ">3.9, <4.0",  sceptre 4.2.X started getting this error.

```
❯ poetry update
Updating dependencies
Resolving dependencies... (15.1s)

  SolverProblemError

  The current project's Python requirement (>=3.9.0,<4.0) is not compatible with some of the required packages Python requirement:
    - sceptre requires Python >=3.7,<3.12, so it will not be satisfied for Python >=3.12,<4.0
    - sceptre requires Python >=3.7,<3.12, so it will not be satisfied for Python >=3.12,<4.0

  Because no versions of sceptre match >4.2.0,<4.2.1 || >4.2.1,<5.0.0
   and sceptre (4.2.0) requires Python >=3.7,<3.12, sceptre is forbidden.
  So, because sceptre (4.2.1) requires Python >=3.7,<3.12
   and pcbaton depends on sceptre (^4.2.0), version solving failed.
```

I tried adjusting the python range to <3.12 but caused other issues, so had to pin sceptre to 4.1.X

`sceptre = "^4.1.0"`

Since python 3.12 doesn't even exist, is it possible to have to ceiling at python <4.0.  I understand this adds risk when a new python minor version is release, but considering the current pattern, we'll be stuck on 4.1 indefinitely cause the ranges will never match if sceptre keeps chasing the latest python minor version and everybody else just does `python = '>=3.X.X,<4.0'`

### Your environment
4.1.0
3.9.9
macosx

### Steps to reproduce
poetry update

### Expected behaviour
Upgrading to latest sceptre

### Actual behaviour
pinning to 4.1.0 cause doesn't have the < 3.12 restriction

**Comment by jfalkenstein** [comment]
Hi @pc-fmarin, on this I think we'll have to say that we cannot and will not do this. I don't really see the point in allowing all future minor versions of Python... such would assume there won't be any breaking or incompatible changes between now and Python 4. History proves that assumption to be pure hubris. 

For the sake of stability of Sceptre, we always make sure to explicitly test and certify that Sceptre is compatible with each Python version. Even upgrading to support Python 3.10 required us to make changes to core Sceptre code in order for it not to be broken. I do not foresee supporting 3.12 to be any different. While some libraries make sense to pin up to the next major version, we cannot do this with the Python version itself.

I'll also note that Sceptre will perform most at its most stable if it is installed into its own virtual environment as a standalone application, not mixed in with your application dependencies. This is not out of step with other IaC tools. For example, AWS SAM CLI recommends that it be installed in its own virtual environment rather than pip-installed into the same environment as other dependencies. I would recommend that you establish a separate virtual environment for Sceptre and then there won't be any version incompatibilities. Alternatively, (just from a pure application architecture best-practices perspective), I'd encourage you to not use `>3.9, <4.0` as your python dependency.

**Comment by thetumper** [comment]
FWIW, we just ran into deploy failures (first time that sceptre >= 4.2.0 was picked up by our pipeline):

ERROR: botocore 1.31.1 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 2.0.3 which is incompatible.

After seeing this issue, tried with <4.2.0, and that resolved it.  Suspecting the poetry update?  I don't disagree with the suggestion to use virtual environments, but we are not python devs...and trying to figure out this stuff is more difficult as a result.  :(

**Comment by jfalkenstein** [comment]
If you want to avoid using virtual environments, I'd suggest using [pipx](https://pypa.github.io/pipx/)... which is used for installing tools (like Sceptre) into isolated, independent virtual environments. It should make it a lot easier to install Sceptre for use without mixing it with other environments.
