### ISSUE TITLE
Support for templates outside Sceptre project directory

### ISSUE THREAD

**Issue by theseanything** [Sceptre/sceptre#213]
Currently Sceptre only supports templates located within the current working Sceptre project directory. Providing support to specify a template outside the project directory would allow more flexibility when managing templates. An external templates folder would allow them to be shared between multiple Sceptre projects locally. Additionally the external folder be managed in a separate git repository for sharing and distribution of templates. 

### Possible Implementation:
Having a `external_template_folder` property in `config.yaml` or the proposed `sceptre.yaml` file. Then all references of `template_path` in stack configs are relative to that folder. If the `external_template_folder` property is absent then Sceptre defaults to the `templates` folder within the current project folder.

**Comment by mike-rsi** [comment]
Will `external_template_folder` also be definable/overridable in stack configs?  Within the same project, it would be nice if certain stacks could use shared templates (i.e. from external directories) while other stacks use project-specific templates from within the Sceptre project directory. Or maybe even easier, have you thought about just supporting `../` in values for the `template_path` and not needing a new configuration option to specify a path for external templates?

A less critical thought: if you go with the new configuration option, would the key `external_template_directory` be a better choice than `external_template_folder`, seeing as "folder" is typically a GUI-related term?

**Comment by johnculkin** [comment]
+1 to 'it would be nice if certain stacks could use shared templates (i.e. from external directories) while other stacks use project-specific templates"

**Comment by theseanything** [comment]
Good point @mike-rsi. Agree with `directory` instead of `folder`.

Maybe could have different naming:
```yaml
template_path: networking/vpc.yaml
```
or 
```yaml
external_template_path: networking/vpc.yaml
```

**Comment by theseanything** [comment]
Another issue with re-usability is that `external_template_directory` probably won't be the same for a sceptre project on different local machines. So thinking it might be sensible to make this property set a system-wide level i.e. have an environment_variable `SCEPTRE_TEMPLATE_DIR`.

**Comment by b-t-g** [comment]
@theseanything, I've thought about it a little more and I think there may be a usability issue with just having an environment variable to denote a directory containing the desired template.

Consider the following two `SCEPTRE_TEMPLATE_DIR`s:

```
.
├── ec2.yaml
└── vpc.yaml
```

and

```
.
├── project1
│   ├── ec2.yaml
│   └── vpc.yaml
└── project2
    ├── api_gateway.yaml
    ├── ec2.yaml
    └── rds.yaml
```
I'm imaging the case when someone first joins a project (the first external template directory) and someone who is possibly on multiple projects (the second external template directory).

In this example, where would Sceptre know where to look for the second external directory when we say `external_template_directory: ec2.yaml` or whatever the desired syntax would be.

Enforcing a consistent style of local directory organization (which ostensibly shouldn't affect functionality) seems a bit heavy-handed to me.

Possible solution: Since this feature is supposed facilitate reuse and sharing of templates, there ought to be a source of truth for the templates being shared. Thus, why not just point to that source of truth, store the result locally somewhere, and then have Sceptre proceed as normally from there?

**Comment by b-t-g** [comment]
If someone is trying to implement this functionality where both repositories are version controlled in git, then [https://git-scm.com/docs/git-submodule](submodules) or [https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging](subtree merging) may be of interest to you depending on your specific workflow.

**Comment by whistler** [comment]
Another possible solution could be to update template path to support fetching templates from a URL.
e.g.

    template_path: https://raw.githubusercontent.com/username/templates/master/vpc.yaml

This way you could support both project-specific templates in the `templates` directory as well as shared templates stored on git, S3 or an artefact repository.

**Comment by jpedro** [comment]
The `template_path` could be resolved from a comma separated *list of directories* not just a single one, optionally defined in `config.yml` defaulting to the current `./templates`. The code would then resolve the `template_path` according that list, first-found first-used basis.

This allow a hierarchy to be defined, with base templates (shared via a git submodule, a git repo, a common folder location or a remote http location) and local templates overriding locally the shared ones if the order dictate so.

**Comment by craighurley** [comment]
I have encountered a setup where a single repository contains multiple workloads, each with their own sceptre directory.  E.g.

```
workloads
├── workload-a
│   ├── config
│   └── templates
└── workload-b
    ├── config
    └── templates
```

I'm not a fan of that setup because it limits the ability to easily reuse templates and `launch` en masse.  If it were possible to tell sceptre to use an external template folder, the structure could be changed to this, which would be much better for template resuse:

```
workloads
├── workload-b
│   └── config
├── workload-b
│   └── config
└── templates
```

**Comment by adnanhb** [comment]
I can look into resolving this task, can somebody assign this task to me?

**Comment by zaro0508** [comment]
hey @adnanhb i believe this issue is resolved by PR 864 .  How about just help review and test that one?

**Comment by campanellaf** [comment]
Any updates on this? Is it possible to refer to a shared folder within the same repo but outside the project?

projects
├── project-a
│   ├── config
└── project-b
    ├── config
    └── templates

I was able to refer to project-b/templates from project-a by using:

template_path: ../project-b/templates/template.json

Is it still possible to achieve this in V2? If it is possible, how?

**Comment by campanellaf** [comment]
Anyone?
