### ISSUE TITLE
Request - a way automatically delete stacks that have been removed from config.

### ISSUE THREAD

**Issue by akdor1154** [Sceptre/sceptre#342]
Our workflow is pretty simple (and pretty standard from what I understand) - we have a bunch of git repos with one (reasonably) independent Sceptre project per-repo. Our CI system runs `sceptre launch-env` on the repo on each commit to master. This all works reasonably well.

However, what happens when we want to remove a stack (or equivalently, rename a stack, => remove then redeploy)?

Currently I don't think there is a way to represent this in sceptre config. Automatic discovery and deletion of stacks that exist but no longer are in config is a bit scary, but maybe an approach could be to have in stack config a `delete: true` flag or something? The ability to have stacks exist with no resources would also be awesome but I don't think AWS is going to change this restriction any time soon.

Has anyone else come across this use case? It's tending towards us wanting to use sceptre a bit like Terraform.

**Comment by ngfgrant** [comment]
Hey @akdor1154 

I think this is something we can look at as we move Sceptre forward. Would you be willing to suggest a rough implementation for this here and we could discuss in a bit more detail?

**Comment by akdor1154** [comment]
Yep.
Flow:
 - if project allows auto-deletion (step 0)
 - deployedStacks = find existing deployed stacks that are part of project (step 1)
 - toDeployStacks = find stacks that are to be deployed as part of project in working directory (step 2)
 - undeploy all stacks in the set `deployedStacks - toDeployStacks` (do comparison by stack name) (step 3)
 - launch-env as normal (step 4)

## auto-detetion:
I reckon on by default, but allow opt-out with a stack or env option.

## find deployed stacks (step 1)
Two approaches here
 1)
    - find all cfn stacks with name prefixed with project code
 2)
    - tag any deployed sceptre stack with "sceptre:project-code: {project code}"
    - find all cfn stacks with that tag.
I think both those operations require enumerating all stacks in the account so may as well do 2?

## undeploy and launch-env (step 3 and 4)
For MVP, could start with simple undeploy and re-deploy. However, this may run into dependency issues. It might be worth considering a more complicated ordering here.

**Comment by nmyster** [comment]
Sounds like a useful idea. Some questions here around where dependencies are managed and also how you track the stacks after the stack config no longer exists.

For example, I like the tag idea but in general, there isn't anything stopping people removing/altering those tags. I guess this is up to the account security and not really a concern for a tool like Sceptre but worth keeping that in mind.

Another way would be to store a list of created stacks in a file like .sceptre/stacks or something but this runs into the same issues you have with state that Terraform has. Could be an option but maybe a rabbit hole.

Auto-deletion is dangerous. I've seen many scenarios where Sceptre is used in conjunction with other methods of CloudFormation creation/deployment. For example, If I deploy a stack that creates a VPC and associated resources, build it and then hand it over to a team who want to have the pure JSON/YAML templates without using Sceptre. Because I'm "done" with the template, maybe I delete it or move the config somewhere else, you might find resources being deleted automatically that shouldn't be which can cause major issues.

**Comment by zaro0508** [comment]
I would love to see this feature.  I've used a tool for jenkins, jenkins-job-builder, that manages jobs similar to how sceptre manages stacks.  Their way of managing jenkins jobs is to cache md5 checksum of all jobs locally on an initial connection.  Then it will update the cache when jobs are added/removed from jenkins.  This allows it to know which jobs exist and which jobs can be removed.  I'm guessing sceptre can work similarly?  

the `jenkins-jobs update` command is similar to `sceptre launch-env`.  The flag that does the trick is `--delete-old          delete obsolete jobs`
https://docs.openstack.org/infra/jenkins-job-builder/execution.html#command-reference

**Comment by ngfgrant** [comment]
With the way we have implemented stack execution in v2 this should be reasonably straight forward. Not sure if it would be worth the effort for v1 but happy to slow at v2. Also would drift detection play a useful role here?

**Comment by wmaroy** [comment]
Any updates on this? Would be interested in this feature.

**Comment by zaro0508** [comment]
related to https://github.com/Sceptre/sceptre/issues/1193

**Comment by zaro0508** [comment]
Closing because this has been fixed with PR #1229
