### ISSUE TITLE
Sceptre Usage Tutorials

### ISSUE THREAD

**Issue by njsnx** [Sceptre/sceptre#372]
As a Sceptre user, I want to be able to learn how to use the tool and its various functions through clear and simple to follow tutorials.

Initial discussion required to what format to use for this. Video tutorials are good but time-consuming to produce and possibly update however easy to see results and follow along. "Text" tutorials are simple to update but assume depending on the tutorial can be lengthy to produce and for users to follow.

**Comment by jeshan** [comment]
Exactly. there's plenty of info here:
https://sceptre.cloudreach.com/latest/docs/install.html

I'm a new user too and the doc site was very helpful to me.

**Comment by nmyster** [comment]
This issue was more to track some tasks we wanted to achieve to improve our docs. Tutorials would focus more on scenarios when to use the various features. 

Some examples:
* Create a full VPC with Subnets, route tables and NAT Gateways using Sceptre, multiple stacks and  Variables
* Using advanced techniques to improve the reusability and readability of your Sceptre/CloudFormation templates
* Writing your first resolver
* How to work with Hooks - Creating your Own

**Comment by fkhokhar** [comment]
I have put together a google doc on how to spin up a vpc, subnet and ec2 using the golden sceptre templates. Just needs some polishing and then it'll be ready for sharing.

 I've also been playing around with custom resolvers and created one that fetches the correct Amazon Linux AMI ID from https://aws.amazon.com/amazon-linux-ami/ based on the region parameter defined in your config.yaml - I've been told to reimplement it using AWS CLI instead of scraping the webpage but once I've figured that out, I'll be posting a doc on how to write and use a custom resolver as well.

**Comment by schotlandzegtja** [comment]
RE: videos being time-consuming to produce, perhaps worth taking a look at https://asciinema.org

**Comment by zaro0508** [comment]
There is a [Get Started](https://docs.sceptre-project.org/dev/docs/get_started.html) section in the docs.  Also, IMO, referencing existing tutorial on the internet from Sceptre docs is the better approach. If you know of a decent tutorial then just PR and add reference to it in the docs. 

Closing because I think this issue is a no-op.
