### ISSUE TITLE
Port SSM resolver to sceptre V2

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#602]
An SSM resolver was created for sceptre V1 in PR https://github.com/cloudreach/sceptre/pull/409   Would be great if we could port this resolver to sceptre V2.

**Comment by zaro0508** [comment]
@ngfgrant could you please suggest an approach on where the resolver should live?  

Should it be a core resolver?
If not, would you like to host a repo in scepter org for it or put it in a contrib folder similar to how it is done in V1?

**Comment by ngfgrant** [comment]
We are going to try and keep the core resolvers to a minimum. Instead I think this would be better suited in its own repository. Cloudreach will be more than happy to host the repo although it can sit anywhere. Also happy to have it be deployed to our PyPi account. I’ve got a lot of the boilerplate for such a project and I’m happy to contribute that to help get this and other similar hooks/resolvers off the ground. 

Within our docs and read me we can create a page that links to various pip installable hooks and resolvers so that others can find useful projects.

Sound ok?

**Comment by zaro0508** [comment]
That would be great @ngfgrant

**Comment by zaro0508** [comment]
@ngfgrant here is the port https://github.com/zaro0508/sceptre-ssm-resolver would be great if sceptre could host this resolver with CI to deploy to PyPi.  Thanks.

**Comment by ngfgrant** [comment]
@zaro0508 we now have our template resolver (https://github.com/Sceptre/sceptre-resolver-template) and the docs on how to use are https://github.com/Sceptre/project/wiki/sceptre-resolver-template.

Would be great to host it in this org. Do you have time to give this a shot? If not I'm happy to move it across. With the template resolver all new resolvers get: test setup, cicd, sonarqube analysis and deploy to pypi for free :)

**Comment by zaro0508** [comment]
@ngfgrant It would help speed things up for me if you could move this initial one over and I can try to do the others when time allows. thanks.

**Comment by zaro0508** [comment]
resolver has been moved to https://github.com/Sceptre/sceptre-ssm-resolver with PR https://github.com/Sceptre/sceptre-ssm-resolver/pull/2

**Comment by ngfgrant** [comment]
Thanks @zaro0508 great work
