### ISSUE TITLE
Cannot reference files from higher up in directory structure

### ISSUE THREAD

**Issue by DamianBis** [Sceptre/sceptre#662]
We have a use case where we would like to include some config that all stacks get..

See below for an example of how we set up. We'd like to have a vpc-base.yaml that is outside of the Dev/Test/etc folders, and then the VPC.yaml inside dev includes the vpc-base YAML file.

├── config
│   ├── vpc-base.yaml
│   └── dev
│    ...  ├── config.yaml
│    ...   └── vpc.yaml
│   └── test
│    ...   ├── config.yaml
│    ...   └── vpc.yaml

Currently this only works if you have the vpc-base.yaml file inside of the same folder as vpc.yaml and using  
<% include vpc-base.yaml %>
this doesn't work when doing 
<% include ../vpc-base.yaml %>

**Comment by 1oglop1** [comment]
Yes this is because jinja `Environment` starts at `stack_config.yaml` I already proposed that it should start at project root as it does with all other frameworks

**Comment by jmourelos** [comment]
The solution proposed by @1oglop1 sounds reasonable to me. If the maintainers are ok with the approach I could prepare a merge request.

**Comment by ngfgrant** [comment]
Yep happy to see a PR for this.

**Comment by mangolas** [comment]
I would very much like to have this feature as well. Is there any work in progress about this?

**Comment by zaro0508** [comment]
I agree with @1oglop1 however just wanted to propose a workaround.  How about putting the file in `config/common/vpc-base.yaml` ?

You can reference dependencies from files in dev folder as:
```
dependencies:
  - common/vpc-base.yaml
```

Also I think PR #864 may fix this issue as well.

**Comment by mangolas** [comment]
Our problem is not about sharing dependency configs but avoiding a lot of copy pasting between different env configs. 

For example we have four environments, and each env has about 10 ECS services, and one ECS config is nearly 100 lines. It's not very nice to maintain and improve the ECS service config if one needs to touch 40 almost similar copies. And basically simplest case is that each ECS service has unique name, nothing more. 

Only way we have figured out on solving this is to have config to set jinja variables and import a jinja 'config-template' which is then parametrised at the jinja level based on the given variables and renders the actual config.

And in order to be able to share those 'config-templates', we have to create symbolic link directory under every config directory that wishes to use those, which this issue proposal would fix.

I'm not quite sure I follow what is happening at #864 and does it help on our DRY problem or not.

**Comment by ngfgrant** [comment]
@mangolas - I can't tell from the original post `tree` but is there a `config.yaml` at the top level of `config` directory?

**Comment by mangolas** [comment]
@ngfgrant We obviously do not have the same tree than in the issue description, but yes, we do have config.yaml at root. 

For example part of our dev env tree looks about like below:
```
config-templates/
  ecs-service.yaml.j2
config/
  dev/
    eu-west-1/
      app/
        ecs-service-x.yaml (which has jinja "include 'config-templates/ecs-service.yaml.j2' ")
        config-templates/ (symlink to <root>/config-templates)
      infra/
        config-templates/ (symlink to <root>/config-templates)
    us-east-1/
      app/
      infra/
```

So it's those symlinks that would be nice to get rid of. 

Whole different story is that sharing common configs should be possible without jinja hacking...

**Comment by zaro0508** [comment]
this is old so closing.  Although i also think this issue is resolved because sceptre now supports a bunch of different ways to import file configurations using resolvers.  The resolvers can reference files from any location.  The configuration files should allow you to reuse vars for multiple environment configs.
