### ISSUE TITLE
Is it possible to inherit configurations?

### ISSUE THREAD

**Issue by alytle** [Sceptre/sceptre#669]
I have read through a bunch of issues about nested configs, but I'm not clear on whether I can do what I want to with sceptre currently.

I have a large project which has about 30 stacks. I've broken the configuration files up into an appropriate subfolder within config (/dev, /prod, /test, etc). The challenge is that since I have 4 environments, I need to maintain the configuration files independently for each environment. This tends to be time consuming and error prone. 

As the vast majority of the configuration parameters are identical between environments, I would rather have my prod configuration 'inherit' from the dev setup, and then override certain values. This would greatly reduce the number of configuration items within the prod config files, and reduce having to echo changes in all configurations when something is updated.

Is this possible currently?

**Comment by mike-rsi** [comment]
You can do this by restructuring your config directory slightly.  Instead of having /dev, /prod, /test etc. just have one config directory for your project, and have every value that is different between environments set by a variable (e.g. `{{ var.env_name }}`) and have one variable file per environment that you pass in with a `--var-file` option (e.g. `sceptre --var-file dev.yaml launch <project dir>`).

A couple changes that come with this method, you probably want to explicitly name your stacks (e.g. `stack_name: {{ var.env_name }}-VpcStack`) which will also require you to use [stack_output_external](https://sceptre.cloudreach.com/latest/docs/resolvers.html#stack_output_external) in place of `stack_output` resolvers (e.g. `VpcId: !stack_output_external {{var.env_name}}-VpcStack::VpcId`.

This is the project structure I've always used with Sceptre.

**Comment by craighurley** [comment]
@alytle have you tried cascading your group config files as described [here](https://sceptre.cloudreach.com/latest/docs/stack_group_config.html); your original structure and the appropriate cascading would work well.
