### ISSUE TITLE
after_create hook behavior

### ISSUE THREAD

**Issue by davidcomerford** [Sceptre/sceptre#712]
Should the after_create hook execute when a stack already exists?
The name suggests it should be run when the stack is created and not when it is skipped over because it already exists.

**Comment by ngfgrant** [comment]
Hey @davidcomerford I believe the `before_` and `after_` hooks will run when the command is triggered rather than the final state of that command. E.g. we have a bunch of commands `create`, `update`, `delete`, `launch` etc. So the hooks read more like `Before the create command is called do x` rather than `When the stack is in the created state do x`

**Comment by davidcomerford** [comment]
That does seem to be how it's working yes. Thanks for clarifying.
Is there any way to have after_create run only when the stack was created? Or do I need to write some logic into the hook to check if it's work needs to be done every time?

**Comment by ngfgrant** [comment]
Probably best to try and handle within the logic of your hook.
