### ISSUE TITLE
stack_output_external issue when export name contains ':'

### ISSUE THREAD

**Issue by RolandOtta** [Sceptre/sceptre#945]
all our existing exports are prefixed with the stackname that created the export.

so we for example have an export `myStack:myExport`. when trying to fetch such an export with `!stack_output_external` i get the following error: The Stack 'myStack' does not have an output named 'myStack:myExport'.

when calling sceptre with `--debug` i actually can see the output

`Outputs: [{'OutputKey': 'LogicalNameOfOutput', 'OutputValue': 'myValue', 'Description': 'description for export', 'ExportName': 'myStack:myExport'},.....`

**Comment by craighurley** [comment]
What does the full `!stack_output_external` line look like?

**Comment by RolandOtta** [comment]
i tried both 

`!stack_output_external network::network:vpcId profileToUse` and `!stack_output_external network::'network:vpcId' profileToUse`

**Comment by craighurley** [comment]
As all my stacks in a project are managed with sceptre, I always use the outputs logical ID and have no issues, e.g. `network::vpcId`.

You seem to be trying to use the a combination of stack name (`network`) and the export name (`network:vpcId`).  If `stack_output_external` is supposed to support this then it appears to be a bug. cc @ngfgrant.

I see your options as one of the following:
- use the outputs logical ID, assuming the source stack is managed by sceptre.
- if you are using the output within your destination cfn template, use `Fn::ImportValue` rather than passing as a parameter via `!stack_output_external`.
- use a custom resolver if the source stack _is not_ managed by sceptre.
- wait for more info from the maintainers.

One other thing I note is that your export name uses stackname + `:` + reference, when all examples I see from AWS use stackname + `-` + reference.

**Comment by RolandOtta** [comment]
thank you for your feedback and suggestions.

probably my example with then export `network:VpcId` was a bad one, because as you already mentioned in that case i simply could `Fn::ImportValue` in the cfn template.
my real life example is much more complex and the reason why i wanted to use `!stack_output_external` was that i have the source stack is in a different aws account than the destination stack.

i already have a workaround in place fetching the export with aws cli in the before_create/before_update hook, writing the result to a file and using the `!file_contents` resolver to use the result as a parameter. but it really feels wrong to do it that way (even if it works).

to be honest i am also not sure about the idea/usage of the `!stack_output_external` resolver. why does this resolver even need the stack name as a parameter? i mean: exports are normally just referenced by the export name. so why does the resolver even need the stack name as parameter?

regarding your note concerning the usage of `:` in the export name: both variants (`:` and `-`) are used in aws docs (for example the join example in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)

**Comment by craighurley** [comment]
I am hoping someone can provide insight on how to use `!stack_output_external` for your scenario, as that with it seems to be written for.

**Comment by RolandOtta** [comment]
ok i think i now found out how to properly use it:

i launched sceptre with the debug option and it showed me the following export

`{'OutputKey': 'VPC', 'OutputValue': 'vpc-XXXXXXXXX', 'Description': 'The VPC id', 'ExportName': 'network:vpcId'}`

i then tried to use the outputkey (VPC), which is basically the logical resource id of the cft instead of the ExportName (network:vpcId) as the second parameter for `!stack_output_external`

so i ended up with 

`!stack_output_external network::VPC profileName`

which magically works.
